[ai]
ai_similarity_enabled = true
ai_similarity_keywords = ""

[settings]
allow_nsfw = false
theme = "dark"
times_to_run = 3
opacity = 0.9
storymode = false
storymodemethod = 1
storymode_max_length = 1000
resolution_w = 1080
resolution_h = 1920
zoom = 1.0

[settings.background]
background_video = "minecraft"
background_audio = "lofi"
background_audio_volume = 0.15
enable_extra_audio = false
background_thumbnail = false
background_thumbnail_font_family = "arial"
background_thumbnail_font_size = 96
background_thumbnail_font_color = "255,255,255"

[settings.tts]
voice_choice = "tiktok"
random_voice = true
elevenlabs_voice_name = "Bella"
elevenlabs_api_key = ""
aws_polly_voice = "Matthew"
streamlabs_polly_voice = "Matthew"
tiktok_voice = "en_us_001"
tiktok_sessionid = "f0d3519dbd5047de815799a5a09677c4"
python_voice = "1"
py_voice_num = "2"
silence_duration = 0.3
no_emojis = false

[reddit.creds]
client_id = "l393ei5GBzhb8czhWQqChA"
client_secret = "yRY5FcwgOMW7-N4_cmBuvLil1Xd_-Q"
username = "InevitableResident24"
password = "1166@omse"
2fa = false

[reddit.thread]
random = false
subreddit = "funny+askreddit+gaming+aww+worldnews+todayilearned+movies"
post_id = ""
max_comment_length = 500
min_comment_length = 1
post_lang = ""
min_comments = 20
